name: React App CI/CD

on:
  push:
    brnaches: [ "main"]
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: [self-hosted, react-mini-runner]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
          
      - name: Creating build
        run: |
          docker compose up -d --build

      

